# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_sets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facesets',
            options={'verbose_name': '人脸库名', 'verbose_name_plural': '人脸库名'},
        ),
    ]
