# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 23:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faces', '0004_auto_20180110_2328'),
        ('face_sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_encode', models.CharField(default='', max_length=3000, verbose_name='面部encode')),
                ('tolerance', models.CharField(default='', max_length=30, verbose_name='结果公差')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('faceset', models.ForeignKey(help_text='储存到对应的人脸库', on_delete=django.db.models.deletion.CASCADE, related_name='compare_facesets', to='face_sets.FaceSets', verbose_name='人脸库')),
                ('related_face', models.ForeignKey(help_text='相关联人脸id', on_delete=django.db.models.deletion.CASCADE, related_name='related_faces', to='faces.FaceInfo', verbose_name='相关联人脸id')),
            ],
            options={
                'verbose_name': '人脸上传',
                'verbose_name_plural': '人脸上传',
            },
        ),
    ]
