# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare_face', '0003_auto_20180111_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareresults',
            name='related_face',
            field=models.ForeignKey(default='25', help_text='相关联人脸id', on_delete=django.db.models.deletion.CASCADE, related_name='related_faces', to='faces.FaceInfo', verbose_name='相关联人脸id'),
        ),
    ]
