# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_face', '0006_compareresults_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareresults',
            name='related_name',
            field=models.CharField(default='', max_length=30, verbose_name='人脸名字'),
        ),
    ]
