# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 00:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('face_sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='用户名')),
                ('goods_front_image_small', models.ImageField(upload_to='upload', verbose_name='用户图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('faceset', models.ForeignKey(help_text='储存到对应的人脸库', on_delete=django.db.models.deletion.CASCADE, related_name='face_sets', to='face_sets.FaceSets', verbose_name='人脸库')),
            ],
            options={
                'verbose_name': '人脸上传',
                'verbose_name_plural': '人脸上传',
            },
        ),
    ]
