# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import faces.models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_auto_20180110_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceinfo',
            name='picture',
            field=models.ImageField(upload_to=faces.models.get_file_path, verbose_name='用户图片'),
        ),
    ]
