# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_auto_20180110_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceinfo',
            name='picture',
        ),
        migrations.AddField(
            model_name='faceinfo',
            name='face_detail',
            field=models.CharField(default='', max_length=1000, verbose_name='面部细节数据'),
        ),
        migrations.AddField(
            model_name='faceinfo',
            name='face_encode',
            field=models.CharField(default='', max_length=3000, verbose_name='面部encode'),
        ),
    ]
