# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0004_auto_20180110_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faceinfo',
            options={'verbose_name': '人脸详细信息', 'verbose_name_plural': '人脸详细信息'},
        ),
    ]
