# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0005_auto_20180111_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceinfo',
            name='face_detail',
            field=models.CharField(default='', max_length=2000, verbose_name='面部细节数据'),
        ),
    ]
